import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# LINE GRAPH 1 - World GDP
plt.figure(figsize=(8,5))
data = pd.read_csv('data04Bsheet.csv')
plt.title('Global GDP (Billions of USD) Over Time', fontdict={'fontweight':'bold', 'fontsize': 18})
plt.plot(data.Year, data['GDP (B US$)'])
plt.xlabel('Year')
plt.ylabel('GDP (billions of USD)')
plt.grid(True)
plt.yscale('linear')
plt.xscale('linear')
plt.xlim(1960, 2020)
plt.ylim(0, 100000)
plt.savefig('economy_img01.png')
plt.show()

# BAR GRAPH 1.5 - Regional World GDP
plt.figure(figsize=(8,7))
data = pd.read_csv('data04Csheet.csv')
plt.title('GDP (billions of USD) by Region', fontdict={'fontweight':'bold', 'fontsize': 18})
plt.bar(data.Region, data['GDP (B US$)'], zorder=3)
plt.ylabel('GDP (billions of USD)')
plt.grid(zorder=0)
plt.yscale('linear')
plt.xticks(rotation=25)
plt.ylim(1000, 27500)
plt.xlim(left=0.5)
plt.savefig('economy_img01_1.png')
plt.show()

# LINE GRAPH 2 - GDP/CAPITA
plt.figure(figsize=(8,5))
data = pd.read_csv('data04Bsheet.csv')
plt.title('Global GDP per Capita (USD) Over Time', fontdict={'fontweight':'bold', 'fontsize': 18})
plt.plot(data.Year, data['GDP/Capita'])
plt.xlabel('Year')
plt.ylabel('GDP/Capita (USD)')
plt.grid(True)
plt.yscale('linear')
plt.xscale('linear')
plt.xlim(1960, 2020)
plt.ylim(0, 12000)
plt.savefig('economy_img02.png')
plt.show()


# LINE GRAPH 3 - World GDP and Inflation Rate
plt.figure(figsize=(8,5))
data = pd.read_csv('data04Bsheet.csv')
plt.title('Global Rate of Inflation and GDP', fontdict={'fontweight':'bold', 'fontsize': 18})
plt.plot(data.Year, data['Inflation Rate'], label='Inflation Rate')
plt.plot(data.Year, data['GDP Growth'], label='GDP Growth Rate')
plt.xlabel('Year')
plt.ylabel('Rate')
plt.grid(True)
plt.yscale('linear')
plt.xscale('linear')
plt.legend()
plt.xlim(1980, 2020)
plt.ylim(-2, 15)
plt.savefig('economy_img03.png')
plt.show()

# BAR GRAPH 3.5 - Regional GDP growth rate
plt.figure(figsize=(8,7))
data = pd.read_csv('data04Csheet.csv')
plt.title('GDP Growth Rate (USD) by Region', fontdict={'fontweight':'bold', 'fontsize': 18})
plt.bar(data.Region, data['GDP Growth'], zorder=3)
plt.ylabel('GDP Growth Rate')
plt.grid(zorder=0)
plt.yscale('linear')
plt.xticks(rotation=25)
plt.ylim(1, 7)
plt.xlim(left=0.5)
plt.savefig('economy_img03_1.png')
plt.show()

# LINE GRAPH 4 - GDP Spedning
plt.figure(figsize=(8,5))
data = pd.read_csv('data04Bsheet.csv')
plt.title('Global GDP Spending on Institutions', fontdict={'fontweight':'bold', 'fontsize': 18})
plt.plot(data.Year, data['Trade of GDP'], label='Trade')
plt.plot(data.Year, data['Manufacturing of GDP'], label='Manufacturing')
plt.plot(data.Year, data['Healthcare of GDP'], label='Healthcare')
plt.plot(data.Year, data['Military Spending of GDP'], label='Military')
plt.xlabel('Year')
plt.ylabel('Percent of GDP Spending')
plt.grid(True)
plt.yscale('linear')
plt.xscale('linear')
plt.xlim(1980, 2020)
plt.ylim(0, 70)
plt.legend()
plt.savefig('economy_img04.png')
plt.show()

# LINE GRAPH 5 - Unemployemtn
plt.figure(figsize=(8,5))
data = pd.read_csv('data04Bsheet.csv')
plt.title('Global Unemployment Rate Over Time', fontdict={'fontweight':'bold', 'fontsize': 18})
plt.plot(data.Year, data['Unemployment'])
plt.xlabel('Year')
plt.ylabel('Unemployment Rate')
plt.grid(True)
plt.yscale('linear')
plt.xscale('linear')
plt.legend()
plt.xlim(1990, 2020)
plt.ylim(4, 6)
plt.savefig('economy_img05.png')
plt.show()